import React from 'react';

const PrivacyPolicyPage = () => {
  const sections = [
    {
      number: 1,
      title: 'Introduction',
      content:
        "Welcome to iVotePK ('we,' 'us,' 'our'). We respect your privacy and are committed to protecting your personal information. This Privacy Policy explains how we collect, use, and safeguard your data when you use our voting platform. By registering and participating in elections on our website, you agree to the practices described in this policy."
    },
    {
      number: 2,
      title: 'Information We Collect',
      subsections: [
        {
          number: '2.1',
          title: 'Personal Information',
          content: 'To register and use the platform, we may collect:',
          list: [
            'Full name',
            'CNIC number and details',
            'Date of birth',
            'Contact information (email, phone number)',
            'Account security credentials'
          ]
        },
        {
          number: '2.2',
          title: 'Authentication Data (WebAuthn)',
          content:
            'We use Web Authentication (WebAuthn) technology to securely verify users. This includes:',
          list: [
            'Device-based authentication credentials (passkeys)',
            'Public-key credentials generated by your device',
            'Authentication confirmations without storing biometric data',
            'No storage of fingerprints or facial images on our servers'
          ]
        },
        {
          number: '2.3',
          title: 'Technical Information',
          content: 'When you use our services, we automatically collect:',
          list: [
            'IP address and browser type',
            'Device and operating system information',
            'Login activity and timestamps',
            'Cookies and session identifiers'
          ]
        }
      ]
    },
    {
      number: 3,
      title: 'How We Use Your Information',
      content: 'We use your information for the following purposes:',
      list: [
        'To verify user identity using secure authentication',
        'To ensure one-person-one-vote integrity',
        'To prevent fraudulent or duplicate voting',
        'To improve platform performance and security',
        'To comply with legal and regulatory obligations'
      ]
    },
    {
      number: 4,
      title: 'Data Security',
      content: 'We apply strong security practices, including:',
      list: [
        'End-to-end encryption',
        'WebAuthn-based passwordless authentication',
        'Role-based access control (RBAC)',
        'Secure server and database configurations',
        'Regular security reviews and audits'
      ]
    },
    {
      number: 5,
      title: 'Information Sharing and Disclosure',
      content: 'Information may be shared only with:',
      list: [
        'Authorized government election authorities',
        'Trusted technical service providers',
        'Legal authorities when required by law'
      ],
      highlight: 'We do not sell, rent, or misuse your personal data.'
    },
    {
      number: 6,
      title: 'Your Rights and Choices',
      content: 'You have the right to:',
      list: [
        'Access your personal data',
        'Request correction of inaccurate information',
        'Request deletion of non-essential data after elections',
        'Understand how your data is used',
        'Use secure authentication without revealing biometric data'
      ]
    }
  ];

  return (
    <div
      style={{
        minHeight: '100vh',
        backgroundColor: '#e9f7ef' // soft green background
      }}
    >
      {/* Header */}
      <section
        style={{
          background:
            'linear-gradient(135deg, var(--primary-green) 0%, #2ecc71 100%)',
          color: 'white',
          padding: '3rem 0',
          textAlign: 'center'
        }}
      >
        <div className="container">
          <h1
            style={{
              fontSize: '3rem',
              fontWeight: '700',
              textShadow: '2px 2px 4px rgba(0,0,0,0.3)'
            }}
          >
            PRIVACY POLICY
          </h1>
        </div>
      </section>

      {/* Content */}
      <div style={{ padding: '3rem 0' }}>
        <div className="container">
          <div style={{ maxWidth: '900px', margin: '0 auto' }}>
            {sections.map((section, index) => (
              <div key={index} className="card" style={{ marginBottom: '2rem' }}>
                <h2
                  style={{
                    color: 'var(--primary-green)',
                    fontSize: '1.8rem',
                    marginBottom: '1rem',
                    borderBottom: '2px solid var(--primary-green)',
                    paddingBottom: '0.5rem'
                  }}
                >
                  {section.number}. {section.title}
                </h2>

                {section.content && (
                  <p
                    style={{
                      color: 'var(--dark-grey)',
                      fontSize: '1rem',
                      lineHeight: '1.7'
                    }}
                  >
                    {section.content}
                  </p>
                )}

                {section.highlight && (
                  <p
                    style={{
                      color: 'var(--primary-green)',
                      fontWeight: 'bold',
                      padding: '1rem',
                      backgroundColor: '#e9f7ef',
                      borderRadius: '8px',
                      border: '2px solid var(--primary-green)'
                    }}
                  >
                    {section.highlight}
                  </p>
                )}

                {section.list && (
                  <ul
                    style={{
                      color: 'var(--dark-grey)',
                      fontSize: '1rem',
                      lineHeight: '1.7',
                      paddingLeft: '1.5rem'
                    }}
                  >
                    {section.list.map((item, i) => (
                      <li key={i}>{item}</li>
                    ))}
                  </ul>
                )}

                {section.subsections &&
                  section.subsections.map((sub, i) => (
                    <div
                      key={i}
                      style={{
                        marginTop: '1.5rem',
                        padding: '1rem',
                        backgroundColor: '#f4fbf7',
                        borderRadius: '8px'
                      }}
                    >
                      <h3
                        style={{
                          color: 'var(--primary-green)',
                          fontSize: '1.3rem'
                        }}
                      >
                        {sub.number} {sub.title}
                      </h3>
                      <p
                        style={{
                          color: 'var(--dark-grey)',
                          lineHeight: '1.7'
                        }}
                      >
                        {sub.content}
                      </p>
                      {sub.list && (
                        <ul style={{ paddingLeft: '1.5rem' }}>
                          {sub.list.map((item, j) => (
                            <li key={j}>{item}</li>
                          ))}
                        </ul>
                      )}
                    </div>
                  ))}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicyPage;
